import type { Locale } from '../domain/locales'

const en = { title: 'AI reflection keys', body: 'Use your own DeepSeek, OpenAI, or Anthropic API key. Yi Path has no shared key, account, or background AI requests.', provider: 'AI provider', providerBody: 'Each provider keeps separate local key and model settings.', key: 'API key', enable: 'Enable AI reflections', enableBody: 'Optional BYOK layer. Every request needs your preview and confirmation.', warningTitle: 'Before using BYOK', warning: ['Session keys live in memory; encrypted saves stay only on this device, and the passphrase is never stored.', 'Only after you press Send, the shown packet and key go directly to the selected provider—never through Yi Path.', 'Local encryption cannot protect against malicious extensions or active XSS.'], send: 'Send to', responding: 'is responding…', error: 'The provider could not complete the request. Yi Path did not log or store the key.' }
export type AiProviderCopy = Omit<typeof en, 'warning'> & { warning: [string, string, string] }
const translated = (overrides: Partial<AiProviderCopy>): AiProviderCopy => ({ ...en, ...overrides, warning: overrides.warning ?? en.warning as [string, string, string] })
const packs: Record<Locale, AiProviderCopy> = {
  en: en as AiProviderCopy,
  bg: translated({ title: 'Ключове за AI размисъл', body: 'Използвайте собствен ключ за DeepSeek, OpenAI или Anthropic. Yi Path няма общ ключ, профил или фонови AI заявки.', provider: 'AI доставчик', providerBody: 'Всеки доставчик има отделни локални настройки за ключ и модел.', key: 'API ключ', enable: 'Включи AI размисли', enableBody: 'Незадължителен BYOK слой. Всяка заявка изисква преглед и потвърждение.', warningTitle: 'Преди BYOK', warning: ['Сесийните ключове са в паметта; криптираните копия остават само на устройството, без да се пази паролата.', 'Само след „Изпрати“ показаният пакет и ключът отиват директно към избрания доставчик — никога през Yi Path.', 'Локалното криптиране не защитава от злонамерени разширения или активен XSS.'], send: 'Изпрати към', responding: 'отговаря…', error: 'Доставчикът не завърши заявката. Yi Path не записва ключа.' }),
  ru: translated({ title: 'Ключи для AI-размышлений', body: 'Используйте собственный ключ DeepSeek, OpenAI или Anthropic. У Yi Path нет общего ключа, аккаунта или фоновых AI-запросов.', provider: 'AI-провайдер', providerBody: 'Для каждого провайдера отдельно хранятся локальные настройки ключа и модели.', key: 'API-ключ', enable: 'Включить AI-размышления', enableBody: 'Необязательный слой BYOK. Каждый запрос требует предпросмотра и подтверждения.', warningTitle: 'Перед BYOK', warning: ['Сессионные ключи хранятся в памяти; зашифрованные копии остаются только на устройстве, пароль не сохраняется.', 'Только после нажатия «Отправить» показанный пакет и ключ идут напрямую выбранному провайдеру — не через Yi Path.', 'Локальное шифрование не защищает от вредоносных расширений или активного XSS.'], send: 'Отправить в', responding: 'отвечает…', error: 'Провайдер не завершил запрос. Yi Path не записывал ключ.' }),
  de: translated({ title: 'Schlüssel für KI-Reflexionen', body: 'Nutze deinen eigenen API-Schlüssel für DeepSeek, OpenAI oder Anthropic. Yi Path hat keinen gemeinsamen Schlüssel, kein Konto und keine Hintergrundanfragen.', provider: 'KI-Anbieter', key: 'API-Schlüssel', enable: 'KI-Reflexionen aktivieren', warningTitle: 'Vor BYOK', send: 'Senden an', responding: 'antwortet…' }),
  it: translated({ title: 'Chiavi per riflessioni IA', body: 'Usa una tua chiave API DeepSeek, OpenAI o Anthropic. Yi Path non ha chiavi condivise, account o richieste in background.', provider: 'Fornitore IA', key: 'Chiave API', enable: 'Attiva riflessioni IA', warningTitle: 'Prima di BYOK', send: 'Invia a', responding: 'sta rispondendo…' }),
  fr: translated({ title: 'Clés de réflexion IA', body: 'Utilisez votre propre clé API DeepSeek, OpenAI ou Anthropic. Yi Path n’a ni clé partagée, ni compte, ni requête en arrière-plan.', provider: 'Fournisseur IA', key: 'Clé API', enable: 'Activer les réflexions IA', warningTitle: 'Avant BYOK', send: 'Envoyer à', responding: 'répond…' }),
  es: translated({ title: 'Claves para reflexiones con IA', body: 'Usa tu propia clave API de DeepSeek, OpenAI o Anthropic. Yi Path no tiene clave compartida, cuenta ni solicitudes en segundo plano.', provider: 'Proveedor de IA', key: 'Clave API', enable: 'Activar reflexiones de IA', warningTitle: 'Antes de BYOK', send: 'Enviar a', responding: 'está respondiendo…' }),
  'pt-PT': translated({ title: 'Chaves para reflexões de IA', body: 'Usa a tua chave API da DeepSeek, OpenAI ou Anthropic. O Yi Path não tem chave partilhada, conta ou pedidos em segundo plano.', provider: 'Fornecedor de IA', key: 'Chave API', enable: 'Ativar reflexões de IA', warningTitle: 'Antes de BYOK', send: 'Enviar para', responding: 'está a responder…' }),
  pl: translated({ title: 'Klucze refleksji AI', body: 'Użyj własnego klucza API DeepSeek, OpenAI lub Anthropic. Yi Path nie ma wspólnego klucza, konta ani żądań w tle.', provider: 'Dostawca AI', key: 'Klucz API', enable: 'Włącz refleksje AI', warningTitle: 'Przed BYOK', send: 'Wyślij do', responding: 'odpowiada…' }),
}
export function aiProviderCopyFor(locale: Locale) { return packs[locale] }
