import type { Locale } from '../domain/locales'

const en = {
  master: 'Another layer of reflection',
  optional: 'Optional AI reflection',
  panelBody: 'A source-bounded second view. Nothing is sent until you review the summary and press Send.',
  masterBody: 'A calm additional study layer grounded only in the reading packet—not an oracle or authoritative translation.',
  length: 'Response length',
  focus: 'What should this layer emphasize?', focusSituation: 'The situation', focusLines: 'Changing lines', focusPractice: 'A practical next step', focusMonthly: 'Monthly review', noteLabel: 'Optional note for this request', noteHint: 'Add a short note (maximum 53 words).', noteCount: 'words',
  short: 'Short', shortHint: '3 sentences',
  medium: 'Medium', mediumHint: '2 short paragraphs',
  long: 'Long', longHint: '3–4 short paragraphs',
  review: 'Review request',
  refresh: 'Refresh preview',
  reviewAgain: 'Refresh preview',
  ready: 'Ready to request another layer',
  notSent: 'Nothing has been sent. Confirm the essentials below before sending.',
  shared: 'Shared with the selected provider',
  readingPacket: 'This reading packet',
  readings: 'readings',
  movingLines: 'moving lines',
  questionIncluded: 'Question included',
  questionExcluded: 'No question included',
  privateExcluded: 'Questions and journal notes excluded',
  disclaimer: 'AI reflection stays separate from the received Chinese and Yi Path editorial. It can be wrong; use it as a prompt, not prediction or advice.',
}

export type AiReflectionExperienceCopy = typeof en
const translated = (overrides: Partial<AiReflectionExperienceCopy>): AiReflectionExperienceCopy => ({ ...en, ...overrides })

const packs: Record<Locale, AiReflectionExperienceCopy> = {
  en,
  bg: translated({ master: 'Майсторът за размисъл на Yi Path', optional: 'Незадължителен AI размисъл', panelBody: 'Втори поглед с ясни източници. Нищо не се изпраща, преди да прегледате обобщението и да натиснете „Изпрати“.', masterBody: 'Спокоен глас за изучаване, основан само на пакета за прочита — не оракул или авторитетен превод.', length: 'Дължина на отговора', short: 'Кратък', shortHint: '3 изречения', medium: 'Среден', mediumHint: '2 кратки абзаца', long: 'Дълъг', longHint: '3–4 кратки абзаца', review: 'Прегледай заявката', reviewAgain: 'Прегледай отново', ready: 'Готово за въпрос към Майстора', notSent: 'Нищо не е изпратено. Потвърдете основното по-долу.', shared: 'Споделя се с избрания доставчик', readingPacket: 'Пакетът за този прочит', readings: 'прочита', movingLines: 'променящи се линии', questionIncluded: 'Въпросът е включен', questionExcluded: 'Няма включен въпрос', privateExcluded: 'Въпросите и дневниковите бележки са изключени', disclaimer: 'AI размисълът е отделен от получения китайски текст и редакционното съдържание на Yi Path. Може да греши; използвайте го като подтик, не като предсказание или съвет.' }),
  ru: translated({ master: 'Мастер размышлений Yi Path', optional: 'Необязательное AI-размышление', panelBody: 'Второй взгляд с привязкой к источникам. Ничего не отправляется, пока вы не проверите сводку и не нажмёте «Отправить».', masterBody: 'Спокойный голос для изучения, основанный только на пакете чтения, — не оракул и не авторитетный перевод.', length: 'Длина ответа', short: 'Кратко', shortHint: '3 предложения', medium: 'Средне', mediumHint: '2 коротких абзаца', long: 'Подробно', longHint: '3–4 коротких абзаца', review: 'Проверить запрос', reviewAgain: 'Проверить снова', ready: 'Готово для вопроса Мастеру', notSent: 'Ничего не отправлено. Сначала подтвердите основное ниже.', shared: 'Передаётся выбранному провайдеру', readingPacket: 'Пакет этого чтения', readings: 'чтений', movingLines: 'меняющихся линий', questionIncluded: 'Вопрос включён', questionExcluded: 'Вопрос не включён', privateExcluded: 'Вопросы и заметки дневника исключены', disclaimer: 'AI-размышление отделено от полученного китайского текста и редакционного материала Yi Path. Оно может ошибаться; используйте его как повод для размышления, а не прогноз или совет.' }),
  de: translated({ master: 'Yi Path Reflexionsmeister', optional: 'Optionale KI-Reflexion', panelBody: 'Eine zweite, quellengebundene Sicht. Nichts wird gesendet, bevor du die Zusammenfassung prüfst und auf Senden drückst.', masterBody: 'Eine ruhige Studienstimme, die sich nur auf das Lesungspaket stützt – kein Orakel und keine maßgebliche Übersetzung.', length: 'Antwortlänge', short: 'Kurz', shortHint: '3 Sätze', medium: 'Mittel', mediumHint: '2 kurze Absätze', long: 'Lang', longHint: '3–4 kurze Absätze', review: 'Anfrage prüfen', reviewAgain: 'Erneut prüfen', ready: 'Bereit für die Frage an den Meister', notSent: 'Noch wurde nichts gesendet. Prüfe zuerst die Angaben unten.', shared: 'Mit dem gewählten Anbieter geteilt', readingPacket: 'Paket dieser Lesung', readings: 'Lesungen', movingLines: 'Wandellinien', questionIncluded: 'Frage enthalten', questionExcluded: 'Keine Frage enthalten', privateExcluded: 'Fragen und Tagebuchnotizen ausgeschlossen', disclaimer: 'Die KI-Reflexion bleibt vom empfangenen Chinesisch und der Yi-Path-Redaktion getrennt. Sie kann irren; nutze sie als Impuls, nicht als Vorhersage oder Rat.' }),
  it: translated({ master: 'Maestro di riflessione Yi Path', optional: 'Riflessione IA facoltativa', panelBody: 'Un secondo sguardo legato alle fonti. Nulla viene inviato finché non controlli il riepilogo e premi Invia.', masterBody: 'Una voce calma per lo studio, fondata solo sul pacchetto della lettura: non un oracolo né una traduzione autorevole.', length: 'Lunghezza risposta', short: 'Breve', shortHint: '3 frasi', medium: 'Media', mediumHint: '2 paragrafi brevi', long: 'Lunga', longHint: '3–4 paragrafi brevi', review: 'Rivedi richiesta', reviewAgain: 'Rivedi ancora', ready: 'Pronto per chiedere al Maestro', notSent: 'Non è stato inviato nulla. Conferma prima i dati essenziali.', shared: 'Condiviso con il fornitore scelto', readingPacket: 'Pacchetto di questa lettura', readings: 'letture', movingLines: 'linee mobili', questionIncluded: 'Domanda inclusa', questionExcluded: 'Nessuna domanda inclusa', privateExcluded: 'Domande e note del diario escluse', disclaimer: 'La riflessione IA resta separata dal cinese ricevuto e dall’editoriale Yi Path. Può sbagliare: usala come spunto, non come previsione o consiglio.' }),
  fr: translated({ master: 'Maître de réflexion Yi Path', optional: 'Réflexion IA facultative', panelBody: 'Un second regard lié aux sources. Rien n’est envoyé avant votre vérification du résumé et l’appui sur Envoyer.', masterBody: 'Une voix d’étude calme, fondée uniquement sur le paquet de lecture — ni oracle ni traduction faisant autorité.', length: 'Longueur de réponse', short: 'Courte', shortHint: '3 phrases', medium: 'Moyenne', mediumHint: '2 courts paragraphes', long: 'Longue', longHint: '3–4 courts paragraphes', review: 'Vérifier la demande', reviewAgain: 'Vérifier encore', ready: 'Prêt à demander au Maître', notSent: 'Rien n’a été envoyé. Confirmez d’abord les éléments ci-dessous.', shared: 'Partagé avec le fournisseur choisi', readingPacket: 'Paquet de cette lecture', readings: 'lectures', movingLines: 'lignes mutantes', questionIncluded: 'Question incluse', questionExcluded: 'Aucune question incluse', privateExcluded: 'Questions et notes du journal exclues', disclaimer: 'La réflexion IA reste séparée du chinois reçu et de l’éditorial Yi Path. Elle peut se tromper : utilisez-la comme piste, non comme prédiction ou conseil.' }),
  es: translated({ master: 'Maestro de reflexión de Yi Path', optional: 'Reflexión opcional con IA', panelBody: 'Una segunda mirada ligada a las fuentes. No se envía nada hasta que revises el resumen y pulses Enviar.', masterBody: 'Una voz serena de estudio basada solo en el paquete de lectura; no es un oráculo ni una traducción autorizada.', length: 'Longitud de respuesta', short: 'Corta', shortHint: '3 frases', medium: 'Media', mediumHint: '2 párrafos cortos', long: 'Larga', longHint: '3–4 párrafos cortos', review: 'Revisar solicitud', reviewAgain: 'Revisar de nuevo', ready: 'Listo para preguntar al Maestro', notSent: 'No se ha enviado nada. Confirma primero lo esencial.', shared: 'Compartido con el proveedor elegido', readingPacket: 'Paquete de esta lectura', readings: 'lecturas', movingLines: 'líneas mutantes', questionIncluded: 'Pregunta incluida', questionExcluded: 'Sin pregunta incluida', privateExcluded: 'Preguntas y notas del diario excluidas', disclaimer: 'La reflexión con IA permanece separada del chino recibido y del contenido editorial de Yi Path. Puede equivocarse; úsala como estímulo, no como predicción o consejo.' }),
  'pt-PT': translated({ master: 'Mestre de reflexão Yi Path', optional: 'Reflexão opcional de IA', panelBody: 'Um segundo olhar ligado às fontes. Nada é enviado antes de reveres o resumo e carregares em Enviar.', masterBody: 'Uma voz calma de estudo, baseada apenas no pacote da leitura — não é oráculo nem tradução autoritativa.', length: 'Tamanho da resposta', short: 'Curta', shortHint: '3 frases', medium: 'Média', mediumHint: '2 parágrafos curtos', long: 'Longa', longHint: '3–4 parágrafos curtos', review: 'Rever pedido', reviewAgain: 'Rever novamente', ready: 'Pronto para perguntar ao Mestre', notSent: 'Nada foi enviado. Confirma primeiro o essencial.', shared: 'Partilhado com o fornecedor escolhido', readingPacket: 'Pacote desta leitura', readings: 'leituras', movingLines: 'linhas mutáveis', questionIncluded: 'Pergunta incluída', questionExcluded: 'Sem pergunta incluída', privateExcluded: 'Perguntas e notas do diário excluídas', disclaimer: 'A reflexão de IA permanece separada do chinês recebido e do editorial Yi Path. Pode estar errada; usa-a como estímulo, não como previsão ou conselho.' }),
  pl: translated({ master: 'Mistrz refleksji Yi Path', optional: 'Opcjonalna refleksja AI', panelBody: 'Drugie spojrzenie oparte na źródłach. Nic nie zostanie wysłane, dopóki nie sprawdzisz podsumowania i nie naciśniesz Wyślij.', masterBody: 'Spokojny głos do nauki, oparty wyłącznie na pakiecie odczytu — nie wyrocznia ani autorytatywne tłumaczenie.', length: 'Długość odpowiedzi', short: 'Krótka', shortHint: '3 zdania', medium: 'Średnia', mediumHint: '2 krótkie akapity', long: 'Długa', longHint: '3–4 krótkie akapity', review: 'Sprawdź żądanie', reviewAgain: 'Sprawdź ponownie', ready: 'Gotowe do pytania Mistrza', notSent: 'Nic nie wysłano. Najpierw potwierdź poniższe informacje.', shared: 'Udostępniane wybranemu dostawcy', readingPacket: 'Pakiet tego odczytu', readings: 'odczytów', movingLines: 'linii zmiennych', questionIncluded: 'Pytanie uwzględnione', questionExcluded: 'Brak pytania', privateExcluded: 'Pytania i notatki dziennika wykluczone', disclaimer: 'Refleksja AI pozostaje oddzielona od otrzymanego chińskiego tekstu i redakcji Yi Path. Może się mylić; traktuj ją jako impuls, nie przepowiednię ani poradę.' }),
}

export function aiReflectionExperienceCopyFor(locale: Locale) { return packs[locale] }
