import type { Locale } from '../domain/locales'
import { AI_ASSISTED_UI_DRAFT } from './featureCopy'

export type CompanionCopy = {
  eyebrow: string
  title: string
  body: string
  enable: string
  enableBody: string
  choose: string
  cat: string
  dog: string
  size: string
  normal: string
  large: string
  motion: string
  motionBody: string
  sounds: string
  soundsBody: string
  interact: string
  open: string
  close: string
  actions: { cat: [string, string, string]; dog: [string, string, string] }
  privacy: string
  privacyBody: string
  noRequest: string
}

const packs: Record<Locale, { status: 'source-authored' | typeof AI_ASSISTED_UI_DRAFT; copy: CompanionCopy }> = {
  en: { status: 'source-authored', copy: {
    eyebrow: 'Optional AI layer', title: 'Reflection companion', body: 'Choose an original 2.5D tuxedo cat or Labrador companion. It lives at the edge of the screen and gives the optional AI tools a warm, visible home.', enable: 'Enable AI reflections and companion', enableBody: 'The canonical reading remains unchanged and fully usable without AI.', choose: 'Choose your companion', cat: 'Tuxedo cat', dog: 'Labrador dog', size: 'Pet size', normal: 'Normal', large: 'Large · 2×', motion: 'Pet motion', motionBody: 'Allow idle movement and the three interactive animations.', sounds: 'Pet sounds', soundsBody: 'Purrs, chirps, hisses, barks and happy sounds play only after you interact.', interact: 'Spend a moment with your companion', open: 'Open reflection companion', close: 'Close companion', actions: { cat: ['Purr & nuzzle', 'Offer a treat', 'Playful paw'], dog: ['Happy greeting', 'Throw the stick', 'Belly-pat reunion'] }, privacy: 'A friendly shape, still an AI tool', privacyBody: 'The companion never changes the received Chinese text or Yi Path editorial. AI reflections stay in their own clearly labelled layer.', noRequest: 'Opening or playing with the companion never sends data. A provider request happens only after you preview the packet and explicitly ask for a reflection.' } },
  bg: { status: AI_ASSISTED_UI_DRAFT, copy: {
    eyebrow: 'Незадължителен AI слой', title: 'Спътник за размисъл', body: 'Изберете оригинална 2.5D котка смокинг или лабрадор. Спътникът живее в края на екрана и дава топъл, видим дом на незадължителните AI инструменти.', enable: 'Включи AI размислите и спътника', enableBody: 'Каноничният прочит остава непроменен и напълно използваем без AI.', choose: 'Изберете спътник', cat: 'Котка смокинг', dog: 'Лабрадор', size: 'Размер на любимеца', normal: 'Нормален', large: 'Голям · 2×', motion: 'Движение на любимеца', motionBody: 'Позволете спокойното движение и трите интерактивни анимации.', sounds: 'Звуци на любимеца', soundsBody: 'Мъркане, мяукане, съскане, лай и радостни звуци се чуват само след ваше действие.', interact: 'Прекарайте миг със спътника', open: 'Отвори спътника за размисъл', close: 'Затвори спътника', actions: { cat: ['Мъркане и гушкане', 'Дай лакомство', 'Игрива лапа'], dog: ['Радостен поздрав', 'Хвърли пръчката', 'Среща и галене по корема'] }, privacy: 'Приятелски образ, но все пак AI инструмент', privacyBody: 'Спътникът никога не променя получения китайски текст или редакционния текст на Yi Path. AI размислите остават ясно отделени.', noRequest: 'Отварянето и играта със спътника не изпращат данни. Заявка се прави само след преглед и изрично искане за размисъл.' } },
  ru: { status: AI_ASSISTED_UI_DRAFT, copy: {
    eyebrow: 'Необязательный слой ИИ', title: 'Спутник для размышлений', body: 'Выберите оригинального 2.5D кота-смокинга или лабрадора. Спутник живёт у края экрана и становится тёплым, заметным домом для необязательных инструментов ИИ.', enable: 'Включить ИИ-размышления и спутника', enableBody: 'Каноническое чтение остаётся неизменным и полностью доступным без ИИ.', choose: 'Выберите спутника', cat: 'Кот-смокинг', dog: 'Лабрадор', size: 'Размер питомца', normal: 'Обычный', large: 'Большой · 2×', motion: 'Движение питомца', motionBody: 'Разрешить спокойное движение и три интерактивные анимации.', sounds: 'Звуки питомца', soundsBody: 'Мурлыканье, мяуканье, шипение, лай и радостные звуки звучат только после вашего действия.', interact: 'Проведите минуту со спутником', open: 'Открыть спутника для размышлений', close: 'Закрыть спутника', actions: { cat: ['Мурлыкать и ластиться', 'Предложить лакомство', 'Игривая лапа'], dog: ['Радостная встреча', 'Бросить палку', 'Вернуться и подставить живот'] }, privacy: 'Дружелюбный образ, но всё же инструмент ИИ', privacyBody: 'Спутник никогда не меняет полученный китайский текст или редакционный материал Yi Path. ИИ-размышления всегда показаны отдельно.', noRequest: 'Открытие спутника и игра с ним не отправляют данные. Запрос выполняется только после просмотра пакета и явного подтверждения.' } },
  de: { status: AI_ASSISTED_UI_DRAFT, copy: {
    eyebrow: 'Optionale KI-Ebene', title: 'Reflexionsbegleiter', body: 'Wählen Sie eine eigens gestaltete 2,5D-Tuxedo-Katze oder einen Labrador. Der Begleiter lebt am Bildschirmrand und gibt den optionalen KI-Werkzeugen einen warmen, sichtbaren Ort.', enable: 'KI-Reflexionen und Begleiter aktivieren', enableBody: 'Die kanonische Lesung bleibt unverändert und ohne KI vollständig nutzbar.', choose: 'Begleiter wählen', cat: 'Tuxedo-Katze', dog: 'Labrador', size: 'Tiergröße', normal: 'Normal', large: 'Groß · 2×', motion: 'Tierbewegung', motionBody: 'Ruhige Bewegung und drei interaktive Animationen zulassen.', sounds: 'Tiergeräusche', soundsBody: 'Schnurren, Zirpen, Fauchen, Bellen und freudige Laute nur nach Ihrer Interaktion.', interact: 'Ein Augenblick mit Ihrem Begleiter', open: 'Reflexionsbegleiter öffnen', close: 'Begleiter schließen', actions: { cat: ['Schnurren & Anschmiegen', 'Leckerli anbieten', 'Verspielte Pfote'], dog: ['Freudige Begrüßung', 'Stock werfen', 'Wiedersehen & Bauchkraulen'] }, privacy: 'Eine freundliche Gestalt, dennoch ein KI-Werkzeug', privacyBody: 'Der Begleiter verändert weder den überlieferten chinesischen Text noch die Yi-Path-Redaktion. KI-Reflexionen bleiben klar getrennt.', noRequest: 'Öffnen und Spielen sendet keine Daten. Eine Anfrage erfolgt erst nach Vorschau und ausdrücklicher Bestätigung.' } },
  it: { status: AI_ASSISTED_UI_DRAFT, copy: {
    eyebrow: 'Livello IA facoltativo', title: 'Compagno di riflessione', body: 'Scegli un originale gatto tuxedo o un Labrador in 2,5D. Vive sul bordo dello schermo e offre agli strumenti IA facoltativi una presenza calda e visibile.', enable: 'Attiva riflessioni IA e compagno', enableBody: 'La lettura canonica resta invariata e pienamente utilizzabile senza IA.', choose: 'Scegli il compagno', cat: 'Gatto tuxedo', dog: 'Labrador', size: 'Dimensione', normal: 'Normale', large: 'Grande · 2×', motion: 'Movimento', motionBody: 'Consenti il movimento tranquillo e le tre animazioni interattive.', sounds: 'Suoni', soundsBody: 'Fusa, miagolii, soffi, abbai e suoni felici solo dopo un’interazione.', interact: 'Un momento con il tuo compagno', open: 'Apri il compagno di riflessione', close: 'Chiudi il compagno', actions: { cat: ['Fusa e coccole', 'Offri un bocconcino', 'Zampata giocosa'], dog: ['Saluto felice', 'Lancia il bastone', 'Ritorno e grattino alla pancia'] }, privacy: 'Una forma amichevole, sempre uno strumento IA', privacyBody: 'Il compagno non modifica mai il testo cinese ricevuto o l’editoriale Yi Path. Le riflessioni IA restano chiaramente separate.', noRequest: 'Aprire o giocare non invia dati. La richiesta parte solo dopo l’anteprima e una conferma esplicita.' } },
  fr: { status: AI_ASSISTED_UI_DRAFT, copy: {
    eyebrow: 'Couche IA facultative', title: 'Compagnon de réflexion', body: 'Choisissez un chat tuxedo ou un Labrador original en 2,5D. Il vit au bord de l’écran et offre aux outils d’IA facultatifs une présence chaleureuse et visible.', enable: 'Activer les réflexions IA et le compagnon', enableBody: 'La lecture canonique reste inchangée et entièrement utilisable sans IA.', choose: 'Choisissez votre compagnon', cat: 'Chat tuxedo', dog: 'Labrador', size: 'Taille', normal: 'Normale', large: 'Grande · 2×', motion: 'Mouvement', motionBody: 'Autoriser les mouvements calmes et les trois animations interactives.', sounds: 'Sons', soundsBody: 'Ronronnements, miaulements, feulements, aboiements et sons joyeux uniquement après votre interaction.', interact: 'Un moment avec votre compagnon', open: 'Ouvrir le compagnon de réflexion', close: 'Fermer le compagnon', actions: { cat: ['Ronronner et se frotter', 'Offrir une friandise', 'Patte joueuse'], dog: ['Accueil joyeux', 'Lancer le bâton', 'Retour et caresse du ventre'] }, privacy: 'Une forme amicale, toujours un outil d’IA', privacyBody: 'Le compagnon ne modifie jamais le texte chinois reçu ni l’éditorial Yi Path. Les réflexions IA restent clairement séparées.', noRequest: 'L’ouvrir ou jouer avec lui n’envoie aucune donnée. Une requête part uniquement après aperçu et confirmation explicite.' } },
  es: { status: AI_ASSISTED_UI_DRAFT, copy: {
    eyebrow: 'Capa de IA opcional', title: 'Compañero de reflexión', body: 'Elige un gato tuxedo o un Labrador original en 2,5D. Vive en el borde de la pantalla y da a las herramientas de IA opcionales un hogar cálido y visible.', enable: 'Activar reflexiones de IA y compañero', enableBody: 'La lectura canónica permanece intacta y se puede usar por completo sin IA.', choose: 'Elige tu compañero', cat: 'Gato tuxedo', dog: 'Labrador', size: 'Tamaño', normal: 'Normal', large: 'Grande · 2×', motion: 'Movimiento', motionBody: 'Permite el movimiento tranquilo y las tres animaciones interactivas.', sounds: 'Sonidos', soundsBody: 'Ronroneos, maullidos, bufidos, ladridos y sonidos alegres solo después de interactuar.', interact: 'Un momento con tu compañero', open: 'Abrir el compañero de reflexión', close: 'Cerrar el compañero', actions: { cat: ['Ronronear y acurrucarse', 'Ofrecer una golosina', 'Zarpazo juguetón'], dog: ['Saludo feliz', 'Lanzar el palo', 'Regreso y caricia en la barriga'] }, privacy: 'Una forma amistosa, pero sigue siendo una herramienta de IA', privacyBody: 'El compañero nunca modifica el texto chino recibido ni el contenido editorial de Yi Path. Las reflexiones de IA permanecen claramente separadas.', noRequest: 'Abrirlo o jugar no envía datos. La solicitud solo se realiza después de revisar el paquete y confirmarlo expresamente.' } },
  'pt-PT': { status: AI_ASSISTED_UI_DRAFT, copy: {
    eyebrow: 'Camada de IA opcional', title: 'Companheiro de reflexão', body: 'Escolhe um gato tuxedo ou um Labrador original em 2,5D. Vive na margem do ecrã e dá às ferramentas de IA opcionais um lugar caloroso e visível.', enable: 'Ativar reflexões de IA e companheiro', enableBody: 'A leitura canónica permanece inalterada e totalmente utilizável sem IA.', choose: 'Escolhe o companheiro', cat: 'Gato tuxedo', dog: 'Labrador', size: 'Tamanho', normal: 'Normal', large: 'Grande · 2×', motion: 'Movimento', motionBody: 'Permite o movimento tranquilo e as três animações interativas.', sounds: 'Sons', soundsBody: 'Ronronar, miar, bufar, ladrar e sons felizes apenas depois de interagires.', interact: 'Um momento com o teu companheiro', open: 'Abrir o companheiro de reflexão', close: 'Fechar o companheiro', actions: { cat: ['Ronronar e encostar-se', 'Dar um petisco', 'Pata brincalhona'], dog: ['Saudação feliz', 'Atirar o pau', 'Regresso e festa na barriga'] }, privacy: 'Uma forma amigável, mas ainda uma ferramenta de IA', privacyBody: 'O companheiro nunca altera o texto chinês recebido nem o editorial Yi Path. As reflexões de IA ficam claramente separadas.', noRequest: 'Abrir ou brincar não envia dados. O pedido só acontece depois de veres o pacote e confirmares expressamente.' } },
  pl: { status: AI_ASSISTED_UI_DRAFT, copy: {
    eyebrow: 'Opcjonalna warstwa AI', title: 'Towarzysz refleksji', body: 'Wybierz oryginalnego kota tuxedo lub Labradora w 2,5D. Mieszka przy krawędzi ekranu i daje opcjonalnym narzędziom AI ciepłe, widoczne miejsce.', enable: 'Włącz refleksje AI i towarzysza', enableBody: 'Kanoniczna lektura pozostaje niezmieniona i w pełni użyteczna bez AI.', choose: 'Wybierz towarzysza', cat: 'Kot tuxedo', dog: 'Labrador', size: 'Rozmiar', normal: 'Normalny', large: 'Duży · 2×', motion: 'Ruch', motionBody: 'Pozwól na spokojny ruch i trzy interaktywne animacje.', sounds: 'Dźwięki', soundsBody: 'Mruczenie, miauczenie, syczenie, szczekanie i radosne odgłosy tylko po interakcji.', interact: 'Chwila z towarzyszem', open: 'Otwórz towarzysza refleksji', close: 'Zamknij towarzysza', actions: { cat: ['Mruczenie i ocieranie', 'Podaj przysmak', 'Figlarna łapa'], dog: ['Radosne powitanie', 'Rzuć patyk', 'Powrót i głaskanie brzucha'] }, privacy: 'Przyjazny kształt, ale nadal narzędzie AI', privacyBody: 'Towarzysz nigdy nie zmienia otrzymanego tekstu chińskiego ani redakcji Yi Path. Refleksje AI pozostają wyraźnie oddzielone.', noRequest: 'Otwarcie i zabawa nie wysyłają danych. Zapytanie następuje dopiero po podglądzie pakietu i wyraźnym potwierdzeniu.' } },
}

export function companionCopyFor(locale: Locale) {
  return packs[locale].copy
}

export function companionCopyStatus(locale: Locale) {
  return packs[locale].status
}
