import type { Locale } from '../domain/locales'

const en = {
  eyebrow: 'Local notebook protection', title: 'Protect this notebook', body: 'Add an encrypted local lock to readings, journal entries, notes, practice history, and saved AI reflections.', use: 'Use a passphrase', warning: 'If you forget it, the protected data cannot be recovered.', scope: 'Preferences and exported files are not covered by this lock. Local encryption cannot protect against a malicious extension or active XSS.', protected: 'Notebook protection is active', protectedBody: 'Your notebook is encrypted on this device. Lock it now to require the passphrase again.', lockNow: 'Lock notebook now', remove: 'Remove protection', createTitle: 'Create notebook passphrase', createBody: 'Use at least 10 characters. Yi Path never stores this passphrase.', passphrase: 'Passphrase', confirm: 'Confirm passphrase', enable: 'Encrypt and protect', cancel: 'Cancel', mismatch: 'The passphrases do not match.', weak: 'Use at least 10 characters.', busy: 'Encrypting notebook…', removeTitle: 'Remove notebook protection?', removeBody: 'Your notebook will be restored to ordinary local browser storage.', removeConfirm: 'Remove protection', unlockTitle: 'Unlock your notebook', unlockBody: 'Enter the local passphrase for this device.', unlock: 'Unlock notebook', unlockError: 'Could not unlock. Check the passphrase.', forgot: 'Forgot the passphrase?', erase: 'Erase protected notebook', eraseWarning: 'This permanently deletes the encrypted notebook. It cannot be undone.', eraseConfirm: 'Erase permanently', back: 'Keep notebook', loading: 'Checking notebook protection…',
}
export type NotebookLockCopy = typeof en
const translated = (overrides: Partial<NotebookLockCopy>): NotebookLockCopy => ({ ...en, ...overrides })

const packs: Record<Locale, NotebookLockCopy> = {
  en,
  bg: translated({ eyebrow: 'Локална защита на бележника', title: 'Защитете този бележник', body: 'Добавя криптирана локална ключалка за прочити, дневник, бележки, практики и запазени AI размисли.', use: 'Използвай парола', warning: 'Ако я забравите, защитените данни не могат да бъдат възстановени.', protected: 'Защитата на бележника е активна', protectedBody: 'Бележникът е криптиран на това устройство.', lockNow: 'Заключи бележника сега', remove: 'Премахни защитата', createTitle: 'Създайте парола за бележника', passphrase: 'Парола', confirm: 'Потвърдете паролата', enable: 'Криптирай и защити', cancel: 'Отказ', unlockTitle: 'Отключете бележника', unlockBody: 'Въведете локалната парола за това устройство.', unlock: 'Отключи', unlockError: 'Неуспешно отключване. Проверете паролата.', forgot: 'Забравена парола?', erase: 'Изтрий защитения бележник', eraseWarning: 'Това изтрива окончателно криптирания бележник.', eraseConfirm: 'Изтрий окончателно', back: 'Запази бележника', loading: 'Проверка на защитата…' }),
  ru: translated({ eyebrow: 'Локальная защита блокнота', title: 'Защитить этот блокнот', body: 'Добавляет локальную шифрованную блокировку чтений, дневника, заметок, практик и сохранённых ИИ-размышлений.', use: 'Использовать пароль', warning: 'Если вы его забудете, защищённые данные нельзя восстановить.', protected: 'Защита блокнота включена', protectedBody: 'Блокнот зашифрован на этом устройстве.', lockNow: 'Заблокировать сейчас', remove: 'Снять защиту', createTitle: 'Создать пароль блокнота', passphrase: 'Пароль', confirm: 'Повторите пароль', enable: 'Зашифровать и защитить', cancel: 'Отмена', unlockTitle: 'Разблокировать блокнот', unlockBody: 'Введите локальный пароль этого устройства.', unlock: 'Разблокировать', unlockError: 'Не удалось разблокировать. Проверьте пароль.', forgot: 'Забыли пароль?', erase: 'Стереть защищённый блокнот', eraseWarning: 'Зашифрованный блокнот будет удалён навсегда.', eraseConfirm: 'Удалить навсегда', back: 'Сохранить блокнот', loading: 'Проверка защиты…' }),
  de: translated({ eyebrow: 'Lokaler Notizbuchschutz', title: 'Dieses Notizbuch schützen', body: 'Fügt eine lokale verschlüsselte Sperre für Lesungen, Journal, Notizen, Praxisverlauf und gespeicherte KI-Reflexionen hinzu.', use: 'Passphrase verwenden', warning: 'Wenn du sie vergisst, können die geschützten Daten nicht wiederhergestellt werden.', protected: 'Notizbuchschutz ist aktiv', lockNow: 'Notizbuch jetzt sperren', remove: 'Schutz entfernen', createTitle: 'Notizbuch-Passphrase erstellen', passphrase: 'Passphrase', confirm: 'Passphrase bestätigen', enable: 'Verschlüsseln und schützen', cancel: 'Abbrechen', unlockTitle: 'Notizbuch entsperren', unlockBody: 'Gib die lokale Passphrase für dieses Gerät ein.', unlock: 'Notizbuch entsperren', unlockError: 'Entsperren fehlgeschlagen. Prüfe die Passphrase.', forgot: 'Passphrase vergessen?', erase: 'Geschütztes Notizbuch löschen', eraseWarning: 'Das verschlüsselte Notizbuch wird endgültig gelöscht.', eraseConfirm: 'Endgültig löschen', back: 'Notizbuch behalten', loading: 'Notizbuchschutz wird geprüft…' }),
  it: translated({ eyebrow: 'Protezione locale del quaderno', title: 'Proteggi questo quaderno', body: 'Aggiunge un blocco cifrato locale a letture, diario, note, pratiche e riflessioni IA salvate.', use: 'Usa una passphrase', warning: 'Se la dimentichi, i dati protetti non possono essere recuperati.', protected: 'La protezione è attiva', lockNow: 'Blocca ora il quaderno', remove: 'Rimuovi protezione', createTitle: 'Crea la passphrase', passphrase: 'Passphrase', confirm: 'Conferma passphrase', enable: 'Cifra e proteggi', cancel: 'Annulla', unlockTitle: 'Sblocca il quaderno', unlockBody: 'Inserisci la passphrase locale per questo dispositivo.', unlock: 'Sblocca', unlockError: 'Impossibile sbloccare. Controlla la passphrase.', forgot: 'Passphrase dimenticata?', erase: 'Cancella quaderno protetto', eraseWarning: 'Il quaderno cifrato verrà eliminato definitivamente.', eraseConfirm: 'Elimina definitivamente', back: 'Conserva il quaderno', loading: 'Verifica protezione…' }),
  fr: translated({ eyebrow: 'Protection locale du carnet', title: 'Protéger ce carnet', body: 'Ajoute un verrou chiffré local aux tirages, journal, notes, pratiques et réflexions IA enregistrées.', use: 'Utiliser une phrase secrète', warning: 'Si vous l’oubliez, les données protégées sont irrécupérables.', protected: 'La protection du carnet est active', lockNow: 'Verrouiller maintenant', remove: 'Retirer la protection', createTitle: 'Créer la phrase secrète', passphrase: 'Phrase secrète', confirm: 'Confirmer', enable: 'Chiffrer et protéger', cancel: 'Annuler', unlockTitle: 'Déverrouiller le carnet', unlockBody: 'Saisissez la phrase secrète locale de cet appareil.', unlock: 'Déverrouiller', unlockError: 'Échec du déverrouillage. Vérifiez la phrase.', forgot: 'Phrase oubliée ?', erase: 'Effacer le carnet protégé', eraseWarning: 'Le carnet chiffré sera supprimé définitivement.', eraseConfirm: 'Effacer définitivement', back: 'Conserver le carnet', loading: 'Vérification de la protection…' }),
  es: translated({ eyebrow: 'Protección local del cuaderno', title: 'Proteger este cuaderno', body: 'Añade un bloqueo cifrado local a lecturas, diario, notas, prácticas y reflexiones de IA guardadas.', use: 'Usar una frase de acceso', warning: 'Si la olvidas, los datos protegidos no se pueden recuperar.', protected: 'La protección está activa', lockNow: 'Bloquear cuaderno ahora', remove: 'Quitar protección', createTitle: 'Crear frase de acceso', passphrase: 'Frase de acceso', confirm: 'Confirmar frase', enable: 'Cifrar y proteger', cancel: 'Cancelar', unlockTitle: 'Desbloquear el cuaderno', unlockBody: 'Introduce la frase local de este dispositivo.', unlock: 'Desbloquear', unlockError: 'No se pudo desbloquear. Comprueba la frase.', forgot: '¿Olvidaste la frase?', erase: 'Borrar cuaderno protegido', eraseWarning: 'El cuaderno cifrado se eliminará para siempre.', eraseConfirm: 'Borrar definitivamente', back: 'Conservar cuaderno', loading: 'Comprobando protección…' }),
  'pt-PT': translated({ eyebrow: 'Proteção local do caderno', title: 'Proteger este caderno', body: 'Adiciona um bloqueio local encriptado a leituras, diário, notas, práticas e reflexões de IA guardadas.', use: 'Usar uma frase-passe', warning: 'Se a esqueceres, os dados protegidos não podem ser recuperados.', protected: 'A proteção está ativa', lockNow: 'Bloquear caderno agora', remove: 'Remover proteção', createTitle: 'Criar frase-passe', passphrase: 'Frase-passe', confirm: 'Confirmar frase-passe', enable: 'Encriptar e proteger', cancel: 'Cancelar', unlockTitle: 'Desbloquear o caderno', unlockBody: 'Introduz a frase-passe local deste dispositivo.', unlock: 'Desbloquear', unlockError: 'Não foi possível desbloquear. Verifica a frase.', forgot: 'Esqueceste a frase?', erase: 'Apagar caderno protegido', eraseWarning: 'O caderno encriptado será apagado para sempre.', eraseConfirm: 'Apagar definitivamente', back: 'Manter caderno', loading: 'A verificar proteção…' }),
  pl: translated({ eyebrow: 'Lokalna ochrona notatnika', title: 'Chroń ten notatnik', body: 'Dodaje lokalną szyfrowaną blokadę odczytów, dziennika, notatek, praktyk i zapisanych refleksji AI.', use: 'Użyj hasła', warning: 'Jeśli je zapomnisz, chronionych danych nie da się odzyskać.', protected: 'Ochrona notatnika jest aktywna', lockNow: 'Zablokuj notatnik teraz', remove: 'Usuń ochronę', createTitle: 'Utwórz hasło notatnika', passphrase: 'Hasło', confirm: 'Potwierdź hasło', enable: 'Zaszyfruj i chroń', cancel: 'Anuluj', unlockTitle: 'Odblokuj notatnik', unlockBody: 'Wpisz lokalne hasło dla tego urządzenia.', unlock: 'Odblokuj', unlockError: 'Nie udało się odblokować. Sprawdź hasło.', forgot: 'Nie pamiętasz hasła?', erase: 'Wymaż chroniony notatnik', eraseWarning: 'Zaszyfrowany notatnik zostanie trwale usunięty.', eraseConfirm: 'Usuń trwale', back: 'Zachowaj notatnik', loading: 'Sprawdzanie ochrony…' }),
}

export function notebookLockCopyFor(locale: Locale) { return packs[locale] }

