import type { Locale } from '../domain/locales'

const en = {
  quickSettings: 'Pet settings', motion: 'Motion', sound: 'Sound', hide: 'Hide pet', practice: 'Golden paw pause', practiceBody: 'A playful 35-second visual pause—not an I Ching ritual.', moments: 'local moments together',
  practiceEyebrow: 'Companion play practice', practiceTitle: 'Watch the golden paw beckon.', practiceIntro: 'Let your eyes soften as the lucky cat slowly raises its paw, beckons, and returns.', start: 'Begin 35 seconds', pause: 'Pause', resume: 'Continue', restart: 'Again', exit: 'Exit practice', complete: 'A small pause, complete.', privacy: 'This optional visual pause is stored only as a local practice session.', seconds: 'seconds',
}
export type PetExperienceCopy = typeof en
const translated = (overrides: Partial<PetExperienceCopy>): PetExperienceCopy => ({ ...en, ...overrides })

const packs: Record<Locale, PetExperienceCopy> = {
  en,
  bg: translated({ quickSettings: 'Настройки на любимеца', motion: 'Движение', sound: 'Звук', hide: 'Скрий любимеца', practice: 'Златна лапа', practiceBody: 'Игрива 35-секундна визуална пауза — не ритуал от И Дзин.', moments: 'локални мигове заедно', practiceEyebrow: 'Игра със спътника', practiceTitle: 'Вижте как златната лапа ви приканва.', practiceIntro: 'Отпуснете погледа, докато щастливата котка бавно повдига лапа, приканва ви и я връща.', start: 'Започни 35 секунди', pause: 'Пауза', resume: 'Продължи', restart: 'Отново', exit: 'Изход', complete: 'Малката пауза завърши.', privacy: 'Тази пауза се пази само като локална практика.', seconds: 'секунди' }),
  ru: translated({ quickSettings: 'Настройки питомца', motion: 'Движение', sound: 'Звук', hide: 'Скрыть питомца', practice: 'Золотая лапа', practiceBody: 'Игровая визуальная пауза на 35 секунд — не ритуал И Цзин.', moments: 'локальных моментов вместе', practiceEyebrow: 'Игра со спутником', practiceTitle: 'Смотрите, как золотая лапа зовёт.', practiceIntro: 'Смягчите взгляд, пока счастливый кот медленно поднимает лапу, подзывает вас и опускает её.', start: 'Начать 35 секунд', pause: 'Пауза', resume: 'Продолжить', restart: 'Ещё раз', exit: 'Выйти', complete: 'Небольшая пауза завершена.', privacy: 'Эта пауза сохраняется только как локальная практика.', seconds: 'секунд' }),
  de: translated({ quickSettings: 'Tier-Einstellungen', motion: 'Bewegung', sound: 'Ton', hide: 'Tier ausblenden', practice: 'Goldene Pfote', practiceBody: 'Eine spielerische visuelle Pause von 35 Sekunden – kein I-Ging-Ritual.', moments: 'lokale Momente zusammen', practiceTitle: 'Folge der goldenen Pfote.', start: '35 Sekunden beginnen', pause: 'Pause', resume: 'Weiter', restart: 'Noch einmal', exit: 'Beenden', complete: 'Die kleine Pause ist beendet.', seconds: 'Sekunden' }),
  it: translated({ quickSettings: 'Impostazioni pet', motion: 'Movimento', sound: 'Suono', hide: 'Nascondi pet', practice: 'Zampa dorata', practiceBody: 'Una pausa visiva giocosa di 35 secondi, non un rituale I Ching.', moments: 'momenti locali insieme', practiceTitle: 'Segui la zampa dorata.', start: 'Inizia 35 secondi', pause: 'Pausa', resume: 'Continua', restart: 'Ancora', exit: 'Esci', complete: 'Piccola pausa completata.', seconds: 'secondi' }),
  fr: translated({ quickSettings: 'Réglages de l’animal', motion: 'Mouvement', sound: 'Son', hide: 'Masquer', practice: 'Patte dorée', practiceBody: 'Une pause visuelle ludique de 35 secondes, pas un rituel du Yi Jing.', moments: 'moments locaux ensemble', practiceTitle: 'Suivez la patte dorée.', start: 'Commencer 35 secondes', pause: 'Pause', resume: 'Continuer', restart: 'Encore', exit: 'Quitter', complete: 'Petite pause terminée.', seconds: 'secondes' }),
  es: translated({ quickSettings: 'Ajustes de mascota', motion: 'Movimiento', sound: 'Sonido', hide: 'Ocultar mascota', practice: 'Pata dorada', practiceBody: 'Una pausa visual de juego de 35 segundos, no un ritual del I Ching.', moments: 'momentos locales juntos', practiceTitle: 'Sigue la pata dorada.', start: 'Empezar 35 segundos', pause: 'Pausa', resume: 'Continuar', restart: 'Otra vez', exit: 'Salir', complete: 'Pequeña pausa completada.', seconds: 'segundos' }),
  'pt-PT': translated({ quickSettings: 'Definições do animal', motion: 'Movimento', sound: 'Som', hide: 'Ocultar animal', practice: 'Pata dourada', practiceBody: 'Uma pausa visual lúdica de 35 segundos, não um ritual do I Ching.', moments: 'momentos locais juntos', practiceTitle: 'Segue a pata dourada.', start: 'Começar 35 segundos', pause: 'Pausa', resume: 'Continuar', restart: 'Outra vez', exit: 'Sair', complete: 'Pequena pausa concluída.', seconds: 'segundos' }),
  pl: translated({ quickSettings: 'Ustawienia zwierzaka', motion: 'Ruch', sound: 'Dźwięk', hide: 'Ukryj zwierzaka', practice: 'Złota łapa', practiceBody: 'Żartobliwa 35-sekundowa pauza wizualna — nie rytuał I Ching.', moments: 'lokalnych chwil razem', practiceTitle: 'Podążaj za złotą łapą.', start: 'Zacznij 35 sekund', pause: 'Pauza', resume: 'Kontynuuj', restart: 'Jeszcze raz', exit: 'Wyjdź', complete: 'Mała pauza zakończona.', seconds: 'sekund' }),
}

export function petExperienceCopyFor(locale: Locale) { return packs[locale] }
